rename bclm2max bclm-cc (charge cycle), add checks for bclm and no battery

diff --git a/.bin/bclm-cc b/.bin/bclm-cc
--- a/.bin/bclm-cc
+++ b/.bin/bclm-cc
@@ -5,6 +5,15 @@ if [ "$(id -u)" -ne 0 ]; then
     exit 1
 fi
 
+has_battery() {
+    pmset -g batt | grep -q 'InternalBattery'
+}
+
+if ! has_battery; then
+    echo 'no battery found, exiting'
+    exit 1
+fi
+
 is_plugged_and_not_charging() {
     pmset -g batt | grep -q 'AC Power' && pmset -g batt | grep -q 'charged'
 }
@@ -17,7 +26,12 @@ is_not_plugged() {
     pmset -g batt | grep -q 'Battery Power'
 }
 
-get_batpc() {
+if ! type bclm >//dev/null 2>&1; then
+    echo 'bclm command not found, exiting' >&2
+    exit 1
+fi
+
+get_bat_pct() {
     current_capacity=$(ioreg -l | grep -o '"CurrentCapacity" = [0-9]*' | awk '{print $3}')
     max_capacity=$(ioreg -l | grep -o '"MaxCapacity" = [0-9]*' | awk '{print $3}')
     percentage=$(echo "scale=2; ($current_capacity / $max_capacity) * 100" | bc)
@@ -43,10 +57,10 @@ echo "bclm set to 100"
 
 sleep 1
 while is_plugged_and_charging; do
-    echo "battery charging at $(get_batpc)%..."
+    echo "battery charging at $(get_bat_pct)%..."
     sleep 60
 done
 
-echo "battery charged to $(get_batpc)%"
+echo "battery charged to $(get_bat_pct)%"
 bclm write "$default_bclm"
 echo "bclm reset to $default_bclm"
